# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose version

before_script:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt install nodejs
  - node --version
  - pwd

script:
  - docker-compose up --build --abort-on-container-exit

after_script:
  - docker-compose down
