language: node_js
node_js:
- '10'
sudo: required
dist: trusty
install:
- sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- docker-compose version
before_script:
- docker system prune -f
- echo PORT=$PORT >> .env
- echo DATABASE=$DATABASE >> .env
- echo DATABASE_PASSWORD=$DATABASE_PASSWORD >> .env
- echo DATABASE_LOCAL=$DATABASE_LOCAL >> .env
- echo DATABASE_TEST=$DATABASE_TEST >> .env
- echo JWT_SECRET=$JWT_SECRET >> .env
- echo JWT_EXPIRES_IN=$JWT_EXPIRES_IN >> .env
- echo JWT_COOKIE_EXPIRES_IN=$JWT_COOKIE_EXPIRES_IN >> .env
- echo JWT_ISSUER=$JWT_ISSUER >> .env
- echo EMAIL_USERNAME=$EMAIL_USERNAME >> .env
- echo EMAIL_PASSWORD=$EMAIL_PASSWORD >> .env
- echo EMAIL_HOST=$EMAIL_HOST >> .env
- echo EMAIL_PORT=$EMAIL_PORT >> .env
- echo REMOTEUSER=$REMOTEUSER >> .env
- echo REMOTEHOST=$REMOTEHOST >> .env
- echo REMOTE_APP_DIR=$REMOTE_APP_DIR >> .env
script:
- docker-compose up --build --abort-on-container-exit
after_script:
- docker-compose down
- docker system prune -f
before_install:
- openssl aes-256-cbc -K $encrypted_b0d51b9ff91b_key -iv $encrypted_b0d51b9ff91b_iv
  -in deploy.enc -out deploy -d
