language: node_js
node_js:
  - '10'

# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose version

before_script:
  - echo $JWT_SECRET >> .env
  - echo $JWT_EXPIRES_IN >> .env
  - echo $JWT_COOKIE_EXPIRES_IN >> .env
  - echo $JWT_ISSUER >> .env
  - cat env
  - pwd

script:
  - docker-compose up --build --abort-on-container-exit

after_script:
  - docker-compose down
