version: '3'

services:
  app:
    container_name: quickstarter-server
    restart: always
    build: .
    # command: bash -c "node dev-data/import-dev-data.js --import"
    ports:
      - '8080:8080'
    links:
      - mongo
  mongo:
    container_name: quickstarter-mongo-test
    image: mongo
    ports:
      - '27017:27017'
