version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
      - image: mongo:4.0.6
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
        filters:
          branches:
              only:
                - master
jobs:
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Connect To MongoDB image
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'be:94:27:fa:f0:a5:c1:38:42:4d:26:4a:c2:67:59:87'
      - checkout
      - run: sh /home/circleci/project/scripts/copy-env.sh
      - deploy:
          name: Deploying to Digital Ocean
          command: |
            ssh -o "StrictHostKeyChecking no" arms-test@161.35.252.183 "cd ~ && cd grad-students-tracker-api && git pull && cp ../.env . && sh scripts/postDeploy.sh"
    

