version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
      - image: mongo:4.0.6
workflows:
  version: 2
  test:
    jobs:
      - test
jobs:
  test:
    executor: node
    steps:
      - checkout
      - run: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run: npm install
      - run: npm run test
